--TO DO BY ADMIN
/*
DROP USER EXAMPLE018 CASCADE;
CREATE USER EXAMPLE018 IDENTIFIED BY EXAMPLE018;
ALTER USER EXAMPLE018 QUOTA UNLIMITED on USERS;
GRANT CREATE SESSION TO EXAMPLE018;
GRANT CREATE TABLE TO EXAMPLE018;
GRANT CREATE SEQUENCE TO EXAMPLE018;
SELECT * FROM dba_users WHERE USERNAME = 'EXAMPLE018';
*/

SELECT * FROM all_constraints WHERE owner = 'EXAMPLE018';


