--TO DO BY ADMIN
/*
SELECT status FROM v$instance;
ALTER DATABASE OPEN;
DROP USER EXAMPLE018 CASCADE;
CREATE USER EXAMPLE018 IDENTIFIED BY EXAMPLE018;
ALTER USER EXAMPLE018 QUOTA UNLIMITED on USERS;
GRANT CREATE SESSION TO EXAMPLE018;
GRANT CREATE TABLE TO EXAMPLE018;
GRANT CREATE SEQUENCE TO EXAMPLE018;
SELECT * FROM dba_users WHERE USERNAME = 'EXAMPLE018';
*/

/*
 DROP TABLE EXAMPLE018.t_country CASCADE CONSTRAINTS;
CREATE TABLE EXAMPLE018.t_country (
                                      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      country_name varchar(255) NOT NULL
);
GRANT SELECT, INSERT, DELETE ON EXAMPLE018.t_country TO EXAMPLE018;

DROP TABLE EXAMPLE018.t_person CASCADE CONSTRAINTS;
CREATE TABLE EXAMPLE018.t_person (
                                   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   person_name varchar(255) NOT NULL, -- UNIQUE,
                                   country_id integer NOT NULL
);
GRANT SELECT, INSERT, DELETE ON EXAMPLE018.t_person TO EXAMPLE018;

INSERT INTO EXAMPLE018.t_country(country_name) VALUES ('Austria');
INSERT INTO EXAMPLE018.t_country(country_name) VALUES ('Greece');
INSERT INTO EXAMPLE018.t_country(country_name) VALUES ('France');

INSERT INTO EXAMPLE018.t_person(person_name, country_id) VALUES ('Vienna', 1);
INSERT INTO EXAMPLE018.t_person(person_name, country_id) VALUES ('Athens', 2);
INSERT INTO EXAMPLE018.t_person(person_name, country_id) VALUES ('Paris', 3);
INSERT INTO EXAMPLE018.t_person(person_name, country_id) VALUES ('Marseille', 3);


 */

SELECT * FROM all_constraints WHERE owner = 'EXAMPLE018';


