DROP TABLE EXAMPLE018.t_country CASCADE CONSTRAINTS;
CREATE TABLE EXAMPLE018.t_country (
                                      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      country_name varchar(255) NOT NULL
);
GRANT SELECT, INSERT, DELETE ON EXAMPLE018.t_country TO EXAMPLE018;

DROP TABLE EXAMPLE018.t_person CASCADE CONSTRAINTS;
CREATE TABLE EXAMPLE018.t_person (
                                   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   person_name varchar(255) NOT NULL, -- UNIQUE,
                                   country_id integer NOT NULL
);
GRANT SELECT, INSERT, DELETE ON EXAMPLE018.t_person TO EXAMPLE018;

